name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libayatana-appindicator3-dev

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
        
      - name: Build the app
        run: bun run tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }},
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        
      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIVIN: ${{ secrets.DIVIN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'music-player ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version of music-player.'
          releaseDraft: true
          prerelease: false